spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/springbootdb?serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.chubxu.web.entity
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

logging:
  level:
    org.chubxu.web.dao: debug
